[package]
name = "verizon"
version = "0.1.6"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
env_logger = "0.11.2"
log = "0.4.20"
self_update = "0.39.0"
slint = "1.4.1"

[build-dependencies]
slint-build = "1.4.1"
