[package]
name = "verizon"
version = "0.1.12"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
env_logger = "0.11.2"
log = "0.4.20"
self_update = { version = "0.39.0", features = [
    "archive-tar",
    "compression-flate2",
] }
slint = "1.4.1"

[build-dependencies]
slint-build = "1.4.1"
