name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Gzip
        run: |
          mkdir verizon
          mv ./target/release/verizon verizon/
          tar -zcvf ./verizon-x86_64-unknown-linux-gnu.tar.gz verizon/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-x86_64-unknown-linux-gnu.tar.gz

  macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Gzip
        run: |
          mkdir verizon
          mv ./target/release/verizon verizon/
          tar -zcvf ./verizon-x86_64-apple-darwin.tar.gz verizon/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-x86_64-apple-darwin.tar.gz

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Gzip
        run: |
          mkdir verizon
          mv ./target/release/verizon.exe verizon/
          tar -zcvf ./verizon-verizon-x86_64-pc-windows-msvc.tar.gz verizon/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-x86_64-pc-windows-msvc.tar.gz
