name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Rename
        run: mv ./target/release/verizon ./verizon-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-linux
  
  macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Rename
        run: mv ./target/release/verizon ./verizon-macos
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-macos

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/verizon.exe