name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Rename
        run: mv ./target/release/verizon ./verizon-x86_64-unknown-linux-gnu
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-x86_64-unknown-linux-gnu
  
  macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Rename
        run: mv ./target/release/verizon ./verizon-x86_64-apple-darwin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-x86_64-apple-darwin

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Rename
        run: mv ./target/release/verizon.exe ./verizon-x86_64-pc-windows-msvc.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./verizon-x86_64-pc-windows-msvc.exe